## Numpy Array Operations

In [1]:
import numpy as np 

In [5]:
arr = np.array([1, 2, 3 , 4 , 5, 6, 7, 8, 9, 10])
print("Basic Slicing: ", arr[2:7])
print("With Step Slicing: ", arr[1:8:2])
print("With negative indexing Slicing: ", arr[-3])


Basic Slicing:  [3 4 5 6 7]
With Step Slicing:  [2 4 6 8]
With negative indexing Slicing:  8


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Specific element: ", arr_2d[1, 2]) # Specific element:  6
print("Entire Row:", arr_2d[1]) # entire row
print("Entire column:", arr_2d[:, 1]) # column target :, with it's help

Specific element:  6
Entire Row: [4 5 6]
Entire column: [2 5 8]


## Sorting

In [19]:
unsorted = np.array([3, 4, 5, 1, 5, 9, 2,6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2],[ 2, 3]])
print("Sorted 2D array by column:\n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by column:\n", np.sort(arr_2d_unsorted, axis=1))

Sorted Array [1 2 3 4 5 5 6 9]
Sorted 2D array by column:
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by column:
 [[1 3]
 [1 2]
 [2 3]]


## Filter

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[(numbers%2 == 0)]
print("Even numbers:\n", even_number)


Even numbers:
 [ 2  4  6  8 10]


### Filter with mask

In [23]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [27]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where:", numbers[where_result])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where: [ 6  7  8  9 10]


In [34]:
condition_array = np.where(numbers > 5, "True", "False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']



```Python
# the above condition can be understood by this analogy 
# if (condition){
#     "True"
# }else{
#     "False"
# }
```