# Learning Numpy From chai aur code

In [2]:
import numpy as np 


### creating array from list

In [ ]:
arr_1d = np.array([1,2,3,4])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]]) # try to use same type of data in order to perform execution of data faster.
print("2D array: ",arr_2d)

1D array:  [1 2 3 4]
2D array:  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [7]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2 )

np_array = np.array([1, 2, 3]) # element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List operation time: ", time.time()-start)

start = time.time()
np_array = np.arange(100000) * 2
print("\n Numpy operation time: ", time.time()-start)


Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.042005062103271484

 Numpy operation time:  0.0011909008026123047


### creating array from scratch

In [ ]:
zeros = np.zeros((3,4)) # creates a matrice of element 0 of required rows and column
print("Zeros array: \n", zeros)

ones = np.ones((2,3)) # creates a matrice of element 1 of required rows and column
print("One array: \n", ones)

full = np.full((2, 2), 7) # creates a matrice of constant element of required row and column
print("Full array: \n", full)

random = np.random.random((2, 3))
print("Random array: \n", random)

sequence = np.arange(0, 11, 2)
print("Sequence array: \n", sequence)



Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.50247741 0.40229912 0.4520306 ]
 [0.95358119 0.18844964 0.83008852]]
Sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [ ]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6],[7,8]]]) # if more than 2D array then we call it as tensor or simply call it multi dimensional array
print("Tensor: ",tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [20]:
arr = np.array([[1, 2, 3],
               [4, 5, "6.8"]])

print("Shape:", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DataType: ", arr.dtype)

Shape: (2, 3)
Dimension:  2
Size:  6
DataType:  <U21


### Array Reshaping

In [29]:
arr = np.arange(12)
print("Original Array: ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array: \n", reshaped)

flattened = reshaped.flatten()
print("Flattened Array: ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n Raveled Array: ", raveled)

# Transpose 
transpose = reshaped.T
print("\n Transpose Array: \n", transpose)


Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
